# Generated by Django 4.2.9 on 2024-01-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment1',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment2',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('N', 'N')], default='A', max_length=1),
        ),
    ]
