# Generated by Django 4.2.9 on 2024-01-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_comment1_comment_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating_of_comm',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating_post',
            new_name='rating',
        ),
    ]
