# Generated by Django 4.2.9 on 2024-01-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_rating_of_comm_comment_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text_of_comm',
            new_name='text',
        ),
    ]
