# Generated by Django 4.2.9 on 2024-04-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_of_category_en_us',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_of_category_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type_en_us',
            field=models.CharField(choices=[('A', 'A'), ('N', 'N')], default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type_ru',
            field=models.CharField(choices=[('A', 'A'), ('N', 'N')], default='N', max_length=1, null=True),
        ),
    ]
